---
containerd_version: "2.0.4"
runc_version: "1.3.1"
cni_version: "1.4.0"
kubernetes_version: "1.34"

# System parameters
#sysctl_settings:
#  net.bridge.bridge-nf-call-iptables: 1
#  net.ipv4.ip_forward: 1
