---
- name: Configure Kubernetes cluster nodes
  hosts: k8s_cluster
  become: yes
  gather_facts: yes
  
  vars_files:
    - group_vars/all.yml

  roles:
    - { role: swap_kernel_DNS, tags: swap_kernel_DNS }
    - { role: container_runtime, tags: container_runtime }
    - { role: kube_components, tags: kube_components }
