---
- name: Configure Kubernetes cluster nodes
  hosts: k8s_cluster
  become: yes
  gather_facts: yes
  
  vars_files:
    - group_vars/all.yml

  roles:
    - { role: swap_disable, tags: swap_disable }
    - { role: container_runtime, tags: container_runtime }
    - { role: kube_components, tags: kube_components }
#    - { role: test_role, tags: test_role }
