---
# tasks file for container_runtime
# - name: Fix DNS configuration
#   tags: debug_dns
#   lineinfile:
#     path: /etc/resolv.conf
#     regexp: '^nameserver '
#     line: 'nameserver 8.8.8.8'
#     state: present
#   when: fix_dns | bool

- name: Create directories for containerd
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /usr/local/bin
    - /opt/cni/bin
    - /etc/containerd

- name: Download containerd
  get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
    dest: "/tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
    mode: '0644'

- name: Extract containerd
  unarchive:
    src: "/tmp/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: yes
    owner: root
    group: root

- name: Download runc
  get_url:
    url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64"
    dest: "/usr/local/sbin/runc"
    mode: '0755'

- name: Download CNI plugins
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-linux-amd64-v{{ cni_version }}.tgz"
    dest: "/tmp/cni-plugins.tgz"
    mode: '0644'

- name: Extract CNI plugins
  unarchive:
    src: "/tmp/cni-plugins.tgz"
    dest: /opt/cni/bin
    remote_src: yes
    owner: root
    group: root

- name: Download containerd systemd service
  get_url:
    url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
    dest: "/etc/systemd/system/containerd.service"
    mode: '0644'

- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: started
    daemon_reload: yes

- name: Create containerd config directory if it does not exist
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Deploy containerd config from template
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: restart containerd

- name: Verify containerd installation
  command: containerd --version
  register: containerd_version
  changed_when: false

- name: Display containerd version
  debug:
    msg: "Containerd version: {{ containerd_version.stdout }}"

- name: Verify runc installation
  command: runc --version
  register: runc_version
  changed_when: false

- name: Display runc version
  debug:
    msg: "Runc version: {{ runc_version.stdout }}"