---
# tasks file for prepare_node
- name: Disable swap immediately
  command: swapoff -a
  ignore_errors: yes

- name: Disable swap permanently in fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^[^#].*swap'
    line: '#\0'
    backrefs: yes